[package]
name = "Rustris"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
rand = "0.8.5"
simple-easing = "1.0.0"
macroquad = "0.3.25"
lazy_static = "1.4.0"
enum_dispatch = "0.3.8"
